# Generated by Django 6.0.2 on 2026-02-25 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('species', models.CharField(choices=[('trout', 'Trout'), ('salmon', 'Salmon'), ('bass', 'Bass'), ('pike', 'Pike')], max_length=50)),
                ('venue', models.CharField(choices=[('river', 'River'), ('lake', 'Lake'), ('sea', 'Sea'), ('pond', 'Pond')], max_length=50)),
                ('method', models.CharField(choices=[('fly', 'Fly fishing'), ('spin', 'Spinning'), ('bait', 'Bait fishing'), ('trolling', 'Trolling')], max_length=50)),
                ('bait', models.CharField(choices=[('worm', 'Worm'), ('insect', 'Insect'), ('artificial', 'Artificial lure'), ('livebait', 'Live bait')], max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
