# Generated by Django 6.0.2 on 2026-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='length',
            field=models.CharField(blank=True, choices=[('short', 'Short (<10 in)'), ('medium', 'Medium (10-20 in)'), ('long', 'Long (>20 in)')], max_length=20),
        ),
    ]
