# Generated by Django 6.0.2 on 2026-02-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0002_catch_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='catch',
            name='bait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catch.bait'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catch.method'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catch.species'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catch.venue'),
        ),
    ]
