# Generated by Django 6.0.2 on 2026-02-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0003_bait_method_species_venue_alter_catch_bait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
