# Generated by Django 6.0.2 on 2026-02-26 19:39

import catch.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0004_alter_catch_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='length',
            field=catch.models.TolerantDecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
