# Generated by Django 6.0.2 on 2026-02-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0006_clear_old_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='catch_pics/'),
        ),
    ]
