# Generated by Django 6.0.2 on 2026-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0007_catch_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
